### ISSUE TITLE
Duplicate Hair Issue (Riverwood) (1.0.2)

### ISSUE THREAD

**Issue by rwbonesy** [SiraMirai/journey#1]
![Riverwood - Sundas, 11꞉07 AM, 17th of Last Seed, 4E 201](https://user-images.githubusercontent.com/57078429/165444336-571fc5e1-754b-471d-a95b-ad1bfe7aa953.png)
Sven's hair appears to be duplicated or at the very least rendering differently than any of the other NPCs in Riverwood. I have not progressed past Riverwood so I cannot confirm if this issue is present with other NPCs with the same style of hair.

No mods have been added or removed. ENB has been turned off via the software provided. No optional mods have been added.

CPU : Ryzen 3600
GPU : AMD Radeon RX 580
RAM : 16 GB
Drive : SSD (Samsung 860 EVO, 500gb)

**Comment by SiraMirai** [comment]
Regenerated his facegen for 1.0.3 and issueis resolved.
