### ISSUE TITLE
Weapons underneath character

### ISSUE THREAD

**Issue by marpet6137** [SiraMirai/journey#2]
I found a bug. Weapons often appears underneath the character, even when unsheathed. Tested on fresh install of Journey Modlist, (no extra mods added). Staff equipments and shields are usually the ones.
![20220503093450_1](https://user-images.githubusercontent.com/104821157/166418487-2d981e5a-11a0-4833-9024-e8cfa58b8ef2.jpg)
![20220503093701_1](https://user-images.githubusercontent.com/104821157/166418603-8325e3de-de7d-4d09-b4b2-5b648af13eac.jpg)
![20220503093749_1](https://user-images.githubusercontent.com/104821157/166418669-de982ef2-1f4e-4374-920d-dc517e459232.jpg)

**Comment by SiraMirai** [comment]
Could you post your Wabbajack install log? Thanks.

**Comment by marpet6137** [comment]
[Wabbajack.current.log](https://github.com/SiraMirai/journey/files/8614349/Wabbajack.current.log)
This one?

**Comment by SiraMirai** [comment]
I'd suggest letting wabbajack reinstall it. On a fresh install, I haven't been able to replicate, so it's possible a file just got copied wrong.

**Comment by marpet6137** [comment]
i got it reinstalled. it works
