### ISSUE TITLE
Embers-related? Campfire texture issue.

### ISSUE THREAD

**Issue by Rootbiscuit** [SiraMirai/journey#3]
The campfire at the bandit camp near the guardian stones (and I assume others) has a bad texture
![Skyrim - Sundas, 1꞉38 PM, 17th of Last Seed, 4E 201](https://user-images.githubusercontent.com/71526273/169280864-2a202ba7-b2f1-4928-874d-d44e031437e8.png)
.

Ref ID: 00097825

**Comment by SiraMirai** [comment]
Found, Inferno mesh overwriting embers XD. Resolved internally, will release in next bugfix update.

campfire01burning.nif in inferno needs to be marked hidden.
