### ISSUE TITLE
CTD when opening Perk Tree

### ISSUE THREAD

**Issue by DecSarge** [SiraMirai/journey#5]
Loving the modlist but when I reach around the Level14 mark whenever I open the perk tree, whether it is to look at the perks or to level up further, the box of text that usually appears doesn't and I get a CTD.

**Comment by SiraMirai** [comment]
What version are you on?

**Comment by DecSarge** [comment]
Quite possibly 1.1.1, I've only just seen the updated change log... apologies.

I'll update the mod list and see if that fixes it

**Comment by DecSarge** [comment]
Yeah that has solved the issue. My mistake for not checking for an update. But thank you for your time and help and thanks for this beautiful mod list

**Comment by SiraMirai** [comment]
Glad that fixed it!
